#!/bin/bash

source functions.sh 

REQUEST=
RUNNING=
USERNAME='ubuntu'

test ! -z $1 && REQUEST="$1"

test -z "$RUNNING" -a -z "$REQUEST" && (echo "No container running and neither any provided in command args."; exit 1)

if [[ ! -z $REQUEST ]]; then
	RUNNING=${REQUEST}

    is_container_active $REQUEST

    if [[ "$?" -ne "0" ]]; then
        echo -n "Container ${REQUEST} is not running. would you like to start it? "
        read answer

        if [ "y" == "$answer" ]; then
            start_container ${REQUEST}
        fi
    fi
fi

for BOX in $RUNNING
do
	echo "Setting up container $BOX"

    mount_local_directory $BOX

	if [ ! -d .lxc -o ! -a .lxc/unsecure-private-key ]; then
        create_ssh_key_pair
	fi

	# injecting key
    copy_ssh_pub_key $BOX $USERNAME

    GUEST=$(get_container_dns_ip $BOX)
    HOST=$(get_host_ip)
	
	echo "Container IP address is $GUEST"

	PORT=$((`echo $BOX | cut -d - -f 2` + 8080 - 2))

	echo Mapping container http port to host "$PORT" port.

	# check iptables rule
    sudo iptables -t nat -C OUTPUT -p tcp -d 0.0.0.0 -o lxcbr0 --dport $PORT -j DNAT --to $GUEST:80

	if [ "$?" -ne "0" ]
	then
        configure_http_port_frwarding  $BOX $PORT
	fi

	echo done.
done;
