#!/bin/bash
RUNPATH=$(dirname $(readlink  -f $0))
source $RUNPATH/functions.sh

function usage {
    echo "Usage: $0 <template>  <target name>"
    echo "Example: "
    echo "    $0 ubuntu my-new-container"
}

if [[ "$#" -ne 2 ]]; then
    usage
    exit 1
fi 

TEMPLATE=$1
CONTAINER=$2

echo "Checking base line ...";
is_template_exists $TEMPLATE
if [[ "$?" -ne "0" ]]; then
    echo "Tempalate container [$TEMPLATE] does not found!"
    exit 1
fi

is_container_exists $CONTAINER
if [[ "$?" -eq "0" ]]; then 
    echo "Container [$CONTAINER] already exists! done."
    exit 1
fi

echo -e "Creating container [$CONTAINER] ..."
create_container $TEMPLATE $CONTAINER

echo -e "Seting up $CONTAINER ..."
config_container $CONTAINER

echo -e "Final touches ..."
generate_mac $CONTAINER

echo -e "done."
