#!/bin/bash

source functions.sh

CONTAINER="ubuntu"
USERNAME="ubuntu"

if [ ! -z "$1" ]; then
	CONTAINER="$1"
fi

if [ ! -z "$2" ]; then
	USENRAME="$2"
fi

# check if container is active 
is_container_active $CONTAINER

if [[ "$?" -ne "0" ]]; then
	echo -n "Container ${CONTAINER} is not running. would you like to start it? "
	read answer

	if [ "y" == "$answer" ]; then
		start_container ${CONTAINER}

		ACTIVE=${CONTAINER}
    else
        exit 255
	fi
else
    ACTIVE=$CONTAINER
fi

if [ ! -z "$ACTIVE" ]; then
	echo "SSH using container: [${CONTAINER}] with username [${USERNAME}]"

    CONTAINER_IP=$(get_container_dns_ip $CONTAINER)
	do_ssh $CONTAINER_IP $USERNAME

	echo "SSH Connection closed!"
fi
