#!/bin/bash

CONTAINER="ubuntu-2"
USERNAME="ubuntu"

function do_ssh {
	IP=$1
	USER=$2

	if [ -a .lxc/unsecure-private-key ]; then
		echo 'SSH Using own key.'
		exec ssh -A -i .lxc/unsecure-private-key ${USER}@${IP}
	else
		exec ssh -A ${USER}@${IP}
	fi
}

function start_container {
	CONTAINER=$1

	$(sudo lxc-start -n ${CONTAINER} -d)
	$(sudo lxc-wait -n ${CONTAINER} -s RUNNING)

	sleep 5
}

if [ ! -z "$1" ]; then
	CONTAINER="$1"
fi

if [ ! -z "$2" ]; then
	USENRAME="$2"
fi

# check if container is active 
ACTIVE=`sudo lxc-ls --active | grep ${CONTAINER}`

if [ -z "$ACTIVE" ]; then
	echo -n "Container ${CONTAINER} is not running. would you like to start it? "
	read answer

	if [ "y" == "$answer" ]; then
		start_container ${CONTAINER}

		ACTIVE=${CONTAINER}
	fi
fi

if [ ! -z "$ACTIVE" ]; then
	echo "SSH using container: [${CONTAINER}] with username [${USERNAME}]"

	CONTAINER_IP=$(host $(echo ${CONTAINER} | sed 's/\.lxc//g') 10.0.3.1 | tail -1 | awk '{print $NF}')

	do_ssh $CONTAINER_IP $USERNAME

	echo "SSH Connection closed!"
fi

#echo ssh -o ProxyCommand nc $(host $(echo ${CONTAINER} | sed 's/\.lxc//g') 10.0.3.1 | tail -1 | awk '{print $NF}') 22


